# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Deploy React to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: bitovi/github-actions-react-to-github-pages@4047c7f17e90e86c4daf2d49befd066f504df07c
      uses: bitovi/github-actions-react-to-github-pages@v1.2.1
          
